### ISSUE TITLE
GameDistribution broken

### ISSUE THREAD

**Issue by fowntain** [Skoolgq/skoolgq.github.io#7]
Games from GameDistribution aren't loading. @omgstacyicanteven @thetatertotgod

**Comment by thetatertotgod** [comment]
rip
________________________________
From: fowntain ***@***.***>
Sent: Tuesday, October 4, 2022 7:48 AM
To: Skoolgq/skoolgq.github.io ***@***.***>
Cc: Gray Brueggeman _ Student - CarrollMS ***@***.***>; Mention ***@***.***>
Subject: [Skoolgq/skoolgq.github.io] GameDistribution broken (Issue #7)


Games from GameDistribution aren't loading. @omgstacyicanteven<https://github.com/omgstacyicanteven> @thetatertotgod<https://github.com/thetatertotgod>

**Comment by thetatertotgod** [comment]
dead af
